package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Room;
import ba.unsa.etf.rpr.exceptions.HotelException;

import java.util.List;

public class RoomManager {
    public Room add(Room r) throws HotelException {
        if (r.getId() != 0){
            throw new HotelException("Can't add Room with ID. ID is autogenerated");
        }
        return DaoFactory.roomDao().add(r);
    }

    public void delete(int id) throws HotelException {
        DaoFactory.roomDao().delete(id);
    }

    public void update(Room r) throws HotelException {
        DaoFactory.roomDao().update(r);
    }

    public List<Room> getAll() throws HotelException{
        return DaoFactory.roomDao().getAll();
    }

    public Room getById(int roomId) throws HotelException{
        return DaoFactory.roomDao().getById(roomId);
    }
    public Room getByDescription(String description) throws HotelException {
        return DaoFactory.roomDao().getByDescription(description);
    }
}
